services:
  location:
    build:
      context: ..
      dockerfile: services/location/docker/Dockerfile
    ports:
      - "50051:50051"
    volumes:
      - ../services/location/cmd/config.json:/home/appuser/config/config.json:ro
    environment:
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - SERVER_PORT=${LOCATION_SERVER_PORT}
      - API_KEY=${LOCATION_API_KEY}
    restart: always
    depends_on:
      redis:
        condition: service_healthy

  ride:
    build:
      context: ..
      dockerfile: services/ride/docker/Dockerfile
    ports:
      - "50052:50052"
    volumes:
      - ../services/ride/cmd/config.json:/home/appuser/config/config.json:ro
    environment:
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - SERVER_PORT=${RIDE_SERVER_PORT}
      - API_KEY=${RIDE_API_KEY}

    restart: always
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy       

  redis:
    image: redis:8-alpine
    container_name: redis 
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  db:
    image: postgres:18-alpine
    container_name: postgres_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ride_db_volume:/var/lib/postgresql/18/data
      - ../services/ride/internal/adapters/pgstore/migrations:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5     

volumes:
  ride_db_volume:      