services:
  redis:
    image: redis:8-alpine
    container_name: redis 
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  db:
    image: postgres:18-alpine
    container_name: postgres_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ride_db_volume:/var/lib/postgresql/18/data
      - ../services/ride/internal/adapters/pgstore/migrations:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  kafka:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: kafka
    ports:
      - "${KAFKA_EXTERNAL_PORT}:${KAFKA_EXTERNAL_PORT}"
      - "${KAFKA_INTERNAL_PORT}:${KAFKA_INTERNAL_PORT}"
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp ${KAFKA_SMP}
      - --memory ${KAFKA_MEMORY}
      - --reserve-memory ${KAFKA_RESERVE_MEMORY}
      - --node-id ${KAFKA_NODE_ID}
      - --check=false
      - --kafka-addr plaintext://0.0.0.0:${KAFKA_INTERNAL_PORT},outside://0.0.0.0:${KAFKA_EXTERNAL_PORT}
      - --advertise-kafka-addr ${KAFKA_ADVERTISE_INTERNAL},${KAFKA_ADVERTISE_EXTERNAL}
      - --set redpanda.auto_create_topics_enabled=${KAFKA_AUTO_CREATE_TOPICS}
    healthcheck:
      test: ["CMD", "rpk", "cluster", "info"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka-ui:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      - KAFKA_BROKERS=${KAFKA_UI_BROKERS}
    depends_on:
      kafka:
        condition: service_healthy

  mongodb:
    image: mongo:8.0
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      
volumes:
  ride_db_volume:
  mongo_data:
