services:
  location:
    build:
      context: ..
      dockerfile: services/location/docker/Dockerfile
    ports:
      - "50051:50051"
    volumes:
      - ../services/location/cmd/config.json:/home/appuser/config/config.json:ro
    environment:
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: always
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:8-alpine
    container_name: redis 
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5