services:
  location:
    build:
      context: ..
      dockerfile: services/location/docker/Dockerfile
    ports:
      - "50051:50051"
    volumes:
      - ../services/location/cmd/config.json:/home/appuser/config/config.json:ro
    environment:
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - SERVER_PORT=${LOCATION_SERVER_PORT}
      - API_KEY=${LOCATION_API_KEY}
      - PROMETHEUS_ADDRESS=${PROMETHEUS_ADDRESS}
      - OPENTELEMETRY_ADDRESS=${OPENTELEMETRY_ADDRESS}
      - TELEMETRY_INTERVAL_SECONDS=${TELEMETRY_INTERVAL_SECONDS}
    restart: always
    depends_on:
      redis:
        condition: service_healthy

  ride:
    build:
      context: ..
      dockerfile: services/ride/docker/Dockerfile
    ports:
      - "50052:50052"
    volumes:
      - ../services/ride/cmd/config.json:/home/appuser/config/config.json:ro
    environment:
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - SERVER_PORT=${RIDE_SERVER_PORT}
      - API_KEY=${RIDE_API_KEY}
      - PROMETHEUS_ADDRESS=${PROMETHEUS_ADDRESS}
      - OPENTELEMETRY_ADDRESS=${OPENTELEMETRY_ADDRESS}
      - TELEMETRY_INTERVAL_SECONDS=${TELEMETRY_INTERVAL_SECONDS}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
      - KAFKA_BROKERS=${KAFKA_BROKERS}
      - KAFKA_ADVERTISE_EXTERNAL=${KAFKA_ADVERTISE_EXTERNAL}
      - KAFKA_ADVERTISE_INTERNAL=${KAFKA_ADVERTISE_INTERNAL}
      - KAFKA_AUTO_CREATE_TOPICS=${KAFKA_AUTO_CREATE_TOPICS}
      - KAFKA_BATCH_SIZE=${KAFKA_BATCH_SIZE}
      - KAFKA_ENABLE_LOGGING=${KAFKA_ENABLE_LOGGING}
      - KAFKA_EXTERNAL_PORT=${KAFKA_EXTERNAL_PORT}
      - KAFKA_INTERNAL_PORT=${KAFKA_INTERNAL_PORT}
      - KAFKA_MEMORY=${KAFKA_MEMORY}
      - KAFKA_NODE_ID=${KAFKA_NODE_ID}
      - KAFKA_RESERVE_MEMORY=${KAFKA_RESERVE_MEMORY}
      - KAFKA_SMP=${KAFKA_SMP}
      - KAFKA_UI_BROKERS=${KAFKA_UI_BROKERS}

    restart: always
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy       

  redis:
    image: redis:8-alpine
    container_name: redis 
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  db:
    image: postgres:18-alpine
    container_name: postgres_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ride_db_volume:/var/lib/postgresql/18/data
      - ../services/ride/internal/adapters/pgstore/migrations:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5     

# The "Bridge": Receives gRPC metrics from your apps and gives them to Prometheus
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol/config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC receiver (where your app pushes)
      - "8889:8889"   # Prometheus exporter (where Prometheus scrapes)

  # The Database for your metrics
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  # The Dashboard
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  kafka:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: kafka
    ports:
      - "${KAFKA_EXTERNAL_PORT}:${KAFKA_EXTERNAL_PORT}"
      - "${KAFKA_INTERNAL_PORT}:${KAFKA_INTERNAL_PORT}"
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp ${KAFKA_SMP}
      - --memory ${KAFKA_MEMORY}
      - --reserve-memory ${KAFKA_RESERVE_MEMORY}
      - --node-id ${KAFKA_NODE_ID}
      - --check=false
      - --kafka-addr plaintext://0.0.0.0:${KAFKA_INTERNAL_PORT},outside://0.0.0.0:${KAFKA_EXTERNAL_PORT}
      - --advertise-kafka-addr ${KAFKA_ADVERTISE_INTERNAL},${KAFKA_ADVERTISE_EXTERNAL}
      - --set redpanda.auto_create_topics_enabled=${KAFKA_AUTO_CREATE_TOPICS}
    healthcheck:
      test: ["CMD", "rpk", "cluster", "info"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka-ui:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      - KAFKA_BROKERS=${KAFKA_UI_BROKERS}
    depends_on:
      kafka:
        condition: service_healthy

volumes:
  ride_db_volume:      