CREATE TABLE countries (
    code VARCHAR(2) PRIMARY,
    currency_code VARCHAR(3) NOT NULL, -- ISO 4217
    is_enabled BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);