syntax = "proto3";

package location.v1;

import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";

option go_package = "github.com/nepeta70/ride-hailing/gen/pb/location/v1";

service LocationService {
  rpc UpdateDriverLocation(DriverLocation) returns (google.protobuf.Empty);
  rpc GetDriverLocation(UserID) returns (DriverLocationWithStatus);
  rpc DeleteDriverLocation(UserID) returns (google.protobuf.Empty);
  rpc SearchNearbyDrivers(SearchNearbyDriversRequest) returns (SearchNearbyDriversResponse);
  rpc UpdateDriverStatus(DriverStatus) returns (google.protobuf.Empty);
}

message DriverLocation {
  // The latitude in degrees. Range: [-90.0, +90.0]
  double latitude = 1;

  // The longitude in degrees. Range: [-180.0, +180.0]
  double longitude = 2;

  // Optional: Horizontal accuracy of the location in meters.
  // Crucial for filtering out "jumpy" GPS data in tunnels or cities.
  float accuracy = 3;
  // Optional: Direction of travel in degrees (0 - 360).
  // Useful for showing the car icon pointing the right way on a map.
  float heading = 4;

  float speed = 5;

  string status = 6;

  google.protobuf.Timestamp status_updated_at = 7;
}

message DriverLocationWithStatus {
  DriverLocation location = 1;

  string status = 2;

  google.protobuf.Timestamp status_updated_at = 3;
}

message DriverStatus {
  string driver_id = 1;
  string status = 2;
}

message UserID {
  // Unique identifier for the user (e.g., driver_id or user_id)
  string user_id = 1;
}

message SearchNearbyDriversRequest {
  // The latitude in degrees. Range: [-90.0, +90.0]
  double latitude = 1;

  // The longitude in degrees. Range: [-180.0, +180.0]
  double longitude = 2;

  // The search radius in kilometers.
  float radius_km = 3;
}

message SearchNearbyDriversResponse {
  message Driver {
    string user_id = 1;
    double latitude = 2;
    double longitude = 3;
    float distance_km = 4; // Distance from the search point in kilometers
    google.protobuf.Timestamp available_since = 5; // timestamp of when the driver became available
  }
  repeated Driver drivers = 1;
}
