syntax = "proto3";

package location.v1;

import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";

option go_package = "github.com/nepeta70/ride-hailing/gen/pb/location/v1";

service LocationService {
  rpc UpdateLocation(UpdateLocationRequest) returns (google.protobuf.Empty);
  rpc GetLocation(LocateRequest) returns (Location);
}

message UpdateLocationRequest {
  // Unique identifier for the entity (e.g., driver_id or user_id)
  string entity_id = 1;

  // The latitude in degrees. Range: [-90.0, +90.0]
  double latitude = 2;

  // The longitude in degrees. Range: [-180.0, +180.0]
  double longitude = 3;

  // Optional: Horizontal accuracy of the location in meters.
  // Crucial for filtering out "jumpy" GPS data in tunnels or cities.
  float accuracy = 4;

  // Optional: Direction of travel in degrees (0 - 360).
  // Useful for showing the car icon pointing the right way on a map.
  float heading = 5;

  // Optional: Speed in meters per second.
  float speed = 6;

  // The exact time the GPS fix was acquired on the device.
  // Don't rely on the server-receive time for real-time tracking!
  google.protobuf.Timestamp captured_at = 7;
}

message Location {
  // The latitude in degrees. Range: [-90.0, +90.0]
  double latitude = 1;

  // The longitude in degrees. Range: [-180.0, +180.0]
  double longitude = 2;
}

message LocateRequest {
  // Unique identifier for the entity (e.g., driver_id or user_id)
  string entity_id = 1;
}
