syntax = "proto3";

package ride.v1;

import "google/protobuf/empty.proto";

option go_package = "github.com/nepeta70/ride-hailing/gen/pb/ride/v1";

service RideService {
  // Rider requests
  rpc EstimateFare(FareEstimateRequest) returns (FareEstimateResponse);
  rpc RequestRide(RideRequest) returns (RideResponse);
  rpc CancelRide(CancelRideRequest) returns (google.protobuf.Empty);

  //Driver requests
  rpc AcceptOrRejectRide(AcceptOrRejectRideRequest) returns (google.protobuf.Empty);
  rpc StartRide(StartRideRequest) returns (google.protobuf.Empty);
  rpc CompleteRide(CompleteRideRequest) returns (google.protobuf.Empty);

  // Fare configuration management
  rpc CreateFareRate(FareRate) returns (FareRate);
  rpc GetFareRates(GetFareRatesRequest) returns (GetFareRatesResponse);
  rpc UpdateFareRate(FareRate) returns (FareRate);
}

message Coordinates {
  double latitude = 1;
  double longitude = 2;
}

message FareEstimateRequest {
  Coordinates pickup_location = 1;
  Coordinates dropoff_location = 2;
}

message FareEstimate {
  string service_type = 1;
  double estimated_fare = 2;
}

message FareEstimateResponse {
  string id = 1;
  int32 estimated_duration_minutes = 2;
  int32 estimated_distance_km = 3;
  string currency = 4;
  repeated FareEstimate fare_estimate = 5;
}

message RideRequest {
  string fare_id = 1;
  string service_type = 2;
  Coordinates pickup_location = 3;
  Coordinates dropoff_location = 4;
}

message RideResponse {
  string ride_id = 1;
}

message CancelRideRequest {
  string ride_id = 1;
}

message AcceptOrRejectRideRequest {
  string ride_id = 1;
  bool accept = 2;
}
message StartRideRequest {
  string ride_id = 1;
}
message CompleteRideRequest {
  string ride_id = 1;
}

message FareRate {
  string id = 1;
  double base_fare = 2;
  double cost_per_km = 3;
  double cost_per_minute = 4;
  double minimum_fare = 5;
  string currency = 6;
  string country = 7;
  string service_type = 8;
}

message GetFareRatesRequest {
  string country = 1;
}

message GetFareRatesResponse {
  repeated FareRate fare_rates = 1;
}

